cluster_name = "labs-nutanix-aws-2"
subnet_name  = "p2p-external-subnet labs-nutanix-aws-2"
#user         = "Prism Central admin user"
#password     = "Password"
#endpoint     = "IP address of Prism Central"
